core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.login_page, name='login'),
    path('register/', views.registration, name='registration'),
    path('logout/', views.logout_view, name='logout'),
    path('company-register/', views.company_register, name='company_register'),
    path('company-register/add-code/', views.add_code, name='add_code'), 
    path('company-register/add-company/', views.add_company, name='add_company'),
    path('company-edit/', views.company_edit_view, name='company_edit' ),
    path('branch/', views.branch_list_view, name='branch'),
    path('branch/edit/<int:pk>/', views.branch_edit_view, name='branch_edit'),
    path('branch/<int:pk>/users/', views.branch_view_users, name='branch_users'),
    
]

pipalite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('', include('core.urls')),
    path('account-settings/', include('userprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.handler404_view'

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('account/', views.account, name='account'),
    path('account-config/', views.account_config, name='config'),
    path('deactivate/', views.account, name='deactivate'), 
]

templates/alert.html
{% load static %}
{% if messages %}
{% for message in messages %}
        <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
{% endfor %}
{% endif %}

templates/base_front.html
{% extends 'html.html' %}
{% load static %}
{% block html %}
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>{% block title %}{% endblock title %}</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon/favicon.ico' %}" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="{% static 'assets/vendor/fonts/boxicons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'assets/vendor/css/core.css' %}" class="template-customizer-core-css" />
    <link rel="stylesheet" href="{% static 'assets/vendor/css/theme-default.css' %}" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />

    <!-- Page CSS -->
    {% block css %}
    {% endblock css%}
    <!-- Page -->
    <link rel="stylesheet" href="{% static 'assets/vendor/css/pages/page-auth.css' %}" />
    
    <!-- Alert CSS -->
    <script src="{% static 'assets/vendor/libs/jquery/jquery.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/toastr.css' %}" media="all">

    <!-- Alert JS -->
    <script type="text/javascript" src="{% static 'assets/js/toastr.min.js' %}"></script>  

    <!-- Helpers -->
    <script src="{% static 'assets/vendor/js/helpers.js' %}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'assets/js/config.js' %}"></script>
  </head>

  <body>
    {% include 'alert.html' %}
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
      <div class="layout-container">
        <!-- Layout container -->
          <!-- Content wrapper -->
          <div class="content-wrapper">
            <!-- Content -->
              {% block content %}
              {% endblock content %}
            <!-- / Content -->
            <!-- Footer -->
              <footer class="content-footer footer bg-footer-theme">
                <div class="container-fluid d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
                  <div class="mb-2 mb-md-0">
                    by Laslov
                  </div>
                  <div>
                    <a href="{% url 'core:logout' %}" class="footer-link me-4">Log Out</a>
                  </div>
                </div>
              </footer>
              <!-- / Footer -->
            <div class="content-backdrop fade"></div>
          </div>
          <!-- Content wrapper -->
        </div>
        <!-- / Layout page -->
    </div>
    <!-- / Layout wrapper -->

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="{% static 'assets/vendor/libs/popper/popper.js' %}"></script>
    <script src="{% static 'assets/vendor/js/bootstrap.js' %}"></script>
    <script src="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'assets/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!-- Page JS -->
    {% block javascript %}
    {% endblock javascript %}

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>

{% endblock html %}

templates/core-404.html
<!DOCTYPE html>

<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->
<html
  lang="en"
  class="light-style"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="../assets/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title>Error - Pages | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="../assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="../assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="../assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="../assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Page -->
    <link rel="stylesheet" href="../assets/vendor/css/pages/page-misc.css" />
    <!-- Helpers -->
    <script src="../assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="../assets/js/config.js"></script>
  </head>

  <body>
    <!-- Content -->

    <!-- Error -->
    <div class="container-xxl container-p-y">
      <div class="misc-wrapper">
        <h2 class="mb-2 mx-2">Page Not Found :(</h2>
        <p class="mb-4 mx-2">Oops! 😖 The requested URL was not found on this server.</p>
        <a href="{% url 'core:home' %}" class="btn btn-primary">Back to home</a>
        <div class="mt-3">
          <img
            src="../assets/img/illustrations/page-misc-error-light.png"
            alt="page-misc-error-light"
            width="500"
            class="img-fluid"
            data-app-dark-img="illustrations/page-misc-error-dark.png"
            data-app-light-img="illustrations/page-misc-error-light.png"
          />
        </div>
      </div>
    </div>
    <!-- /Error -->

    <!-- / Content -->

    <div class="buy-now">
      <a
        href="https://themeselection.com/products/sneat-bootstrap-html-admin-template/"
        target="_blank"
        class="btn btn-danger btn-buy-now"
        >Upgrade to Pro</a
      >
    </div>

    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="../assets/vendor/libs/jquery/jquery.js"></script>
    <script src="../assets/vendor/libs/popper/popper.js"></script>
    <script src="../assets/vendor/js/bootstrap.js"></script>
    <script src="../assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="../assets/vendor/js/menu.js"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->

    <!-- Main JS -->
    <script src="../assets/js/main.js"></script>

    <!-- Page JS -->

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
  </body>
</html>

templates/core-company-get-code.html
{% extends 'base_front.html' %}
{% load static %}
{% block content %}
<div class="px-4 py-5 my-5 text-center">
  <img class="d-block mx-auto mb-4" src="{{ MEDIA_URL }}/defaults/company-default.webp" alt="" width="72" height="57">
  <h1 class="display-5 fw-bold">Add Company Code</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Please get company code from your admin.</p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <form method="POST" action=".">
        {% csrf_token %}
        <div class="input-group">
            <input
            name="companyCode"
              type="text"
              class="form-control"
              placeholder="CODE"
              aria-label="Company Code"
              aria-describedby="button-addon2"
            />
            <button name='getCodeButton' class="btn btn-outline-primary" type="submit" id="button-addon2">Go</button>
        </div>
      </form>
    </div>
    <div class="px-4 py-4">
      <button type="button" class="btn btn-outline-primary" value="Previous Page" onClick="javascript:history.go(-1);">
        <span>
          <i class='tf-icons bx bx-arrow-back'></i>
        </span>
      </button>
    </div>
  </div>
</div>

{% endblock content %}

templates/core-company-settings-branch.html
{% extends 'base.html' %}

{% load static %}


{% block css %}
{% endblock css %}

{% block content %}
<!-- Settings -->
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4">
      <span class="text-muted fw-light">Settings / Company /</span>
      Branch
    </h4>
    <div class="row">
      <div class="col-md-12">
        {% include 'core-company-settings-tab.html' %}
        <div class="row mb-5">
          <!-- Card -->
          {% for branch in branches %}
          <div class="col-md col-xl-6">
            <div class="card position-relative mb-3">
              <div class="row g-0">
                <div class="col-md-4 p-4">
                  <img class="card-img card-img-left" 
                    src="
                    {% if branch.logo.url != '' %}
                      {{ branch.logo.url }}
                    {% else %}
                      {{company.logo.url}}
                    {% endif %}
                    " 
                    alt="Card image" />
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <div class="btn-group position-absolute top-0 end-0 p-2">
                      <button
                        type="button"
                        class="btn btn-outline-light btn-icon dropdown-toggle hide-arrow"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                      >
                        <i class='bx bx-dots-vertical' ></i>
                      </button>
                      <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'core:branch_edit' branch.pk %}">Edit</a></li>
                        <li><a class="dropdown-item" href="{% url 'core:branch_users' branch.pk %}">View Users</a></li>
                        <li>
                          <hr class="dropdown-divider" />
                        </li>
                        <li><a class="dropdown-item" href="javascript:void(0);">Delete</a></li>
                      </ul>
                    </div>
                    <h5 class="card-title">{{ branch.name}}</h5>
                    <p class="card-text">
                      {{ branch.address }}
                    </p>
                    <p class="card-text"><small class="text-muted">{{ branch.tax_id }}</small></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          <!-- Card -->
          <div class="col-md col-xl-4">
            <a href="#">
              <div class="card position-relative mb-3">
                <div class="row g-0">
                  <div class="col-md-4 p-4">
                    <img class="card-img card-img-left" 
                      src="{% static 'assets/img/icons/add.png' %}" 
                      alt="Card image" />
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">Add New Branch</h5>
                      <p class="card-text">
                        Create new branch
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
          <!-- Branch -->
    
          <!-- /Account -->

{% endblock content %}

{% block javascript %}
<script type="text/javascript">
  var loadFile = function(event) {
      var uploadedHeader = document.getElementById('uploadedHeader');
      uploadedHeader.src = URL.createObjectURL(event.target.files[0]);
      uploadedHeader.onload = function() {
        URL.revokeObjectURL(uploadedHeader.src) // free memory
      }
    };
  
  document.addEventListener('DOMContentLoaded', function (e) {
  (function () {
    let companyHeaderLogo = document.getElementById('headerInput');
    const companyFileInput = document.querySelector('.company-file-input')

    if (companyHeaderLogo) {
      const resetImage = companyHeaderLogo.src;
      companyFileInput.onchange = () => {
        if (companyFileInput.files[0]) {
          companyHeaderLogo.src = window.URL.createObjectURL(companyFileInput.files[0]);
        }
      };
    }
  })();
});
  </script>
<script src="{% static 'assets/js/form-basic-inputs.js' %}"></script>
<script src="{% static 'assets/js/pages-account-settings-account.js' %}"></script> 
{% endblock javascript %}

templates/core-company-settings-tab.html
<ul class="nav nav-pills flex-column flex-md-row mb-3">
    <li class="nav-item">
      <a class="nav-link {% if request.path == '/company-edit/' %} active {% endif %}" href="{% url 'core:company_edit' %}">
        <i class="bx bx-user me-1"></i>
        Company
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if request.path == '/branch/'%} active {% endif %}" href="{% url 'core:branch' %}">
        <i class="bx bx-bell me-1"></i> 
        Branch
      </a>
    </li>
  </ul>

templates/core-registration.html
{% extends 'base_front.html' %}
{% load static %}

{% block content %}
<div class="container-xxl">
    <div class="authentication-wrapper authentication-basic container-p-y">
      <div class="authentication-inner">
        <!-- Register Card -->
        <div class="card">
          <div class="card-body">
            <!-- Logo -->
            <div class="app-brand justify-content-center">
              <a href="{% url 'core:login' %}" class="app-brand-link gap-2">
            
              </a>
            </div>
            <!-- /Logo -->
            <h4 class="mb-2 text-center" >Register</h4>
            <!-- error messages -->
                {% for fields, error in form.errors.items %}
                <div class="alert alert-danger my-3 p-1" role="alert">
                    {{ error|striptags }}
                </div>
                {% endfor %}

            <form id="formAuthentication" class="mb-3" action="." method="POST">
                {% csrf_token %}
              <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                {{ form.username }}
              </div>
              <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                {{ form.email }}
              </div>
              <div class="mb-3 form-password-toggle">
                <label class="form-label" for="password">Password</label>
                <div class="input-group input-group-merge">
                  {{ form.password1 }}
                  <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                </div>
              </div>
              <div class="mb-3 form-password-toggle">
                <label class="form-label" for="password">Confirm Password</label>
                <div class="input-group input-group-merge">
                  {{ form.password2 }}
                  <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                </div>
              </div>
              <button class="btn btn-primary d-grid w-100" type="submit">Sign up</button>
            </form>

            <p class="text-center">
              <span>Already have an account?</span>
              <a href="{% url 'core:login' %}">
                <span>Sign in instead</span>
              </a>
            </p>
          </div>
        </div>
        <!-- Register Card -->
      </div>
    </div>
  </div>

  {% endblock content %}

templates/navbar.html
{% load static %}
<nav
class="layout-navbar container-fluid navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
id="layout-navbar"
>
<div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
  <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
    <i class="bx bx-menu bx-sm"></i>
  </a>
</div>

<div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
  <!-- Search -->
  <div class="navbar-nav align-items-center">
    <div class="nav-item d-flex align-items-center">
      <i class="bx bx-search fs-4 lh-0"></i>
      <input
        type="text"
        class="form-control border-0 shadow-none"
        placeholder="Search..."
        aria-label="Search..."
      />
    </div>
  </div>
  <!-- /Search -->

  <ul class="navbar-nav flex-row align-items-center ms-auto">
    <!-- Place this tag where you want the button to render. -->

    <!-- User -->
    <li class="nav-item navbar-dropdown dropdown-user dropdown">
      <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
        <div class="avatar avatar-online">
          <img src="{{ user.userprofile.avatar.url }}" alt class="w-px-40 rounded-circle" />
        </div>
      </a>
      <ul class="dropdown-menu dropdown-menu-end">
        <li>
          <a class="dropdown-item" href="{% url 'userprofile:account' %}">
            <div class="d-flex">
              <div class="flex-shrink-0 me-3">
                <div class="avatar avatar-online">
                  <img src="{{ user.userprofile.avatar.url }}" alt class="w-px-40 rounded-circle" />
                </div>
              </div>
              <div class="flex-grow-1">
                <span class="fw-semibold d-block">{{ user.userprofile.first_name }}</span>
                <small class="text-muted"
                  data-bs-toggle="tooltip"
                  data-popup="tooltip-custom"
                  data-bs-placement="top"
                  class="pull-up"
                  title="{{ request.user.groups.all }}"
                >
                  {{ request.user.groups.all.0.name }} {{ request.user.groups.all.1.name }}</small>
              </div>
            </div>
          </a>
        </li>
        <li>
          <div class="dropdown-divider"></div>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'userprofile:account' %}">
            <i class="bx bx-user me-2"></i>
            <span class="align-middle">My Profile</span>
          </a>
        </li>
        {% if perms.core.can_update_setting %} 
        <li>
          <a class="dropdown-item" href="{% url 'core:company_edit' %}">
            <i class="bx bx-cog me-2"></i>
            <span class="align-middle">Settings</span>
          </a>
        </li>
        {% endif %}
        <li>
          <a class="dropdown-item" href="#">
            <span class="d-flex align-items-center align-middle">
              <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
              <span class="flex-grow-1 align-middle">Billing</span>
              <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>
            </span>
          </a>
        </li>
        <li>
          <div class="dropdown-divider"></div>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'core:logout' %}">
            <i class="bx bx-power-off me-2"></i>
            <span class="align-middle">Log Out</span>
          </a>
        </li>
      </ul>
    </li>
    <!--/ User -->
  </ul>
</div>
</nav>

templates/userprofile_account.html
{% extends 'base.html' %}

{% load static %}


{% block css %}
{% endblock css %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Account Settings /</span> Account</h4>

    <div class="row">
      <div class="col-md-12">
        <ul class="nav nav-pills flex-column flex-md-row mb-3">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'userprofile:account' %}"><i class="bx bx-user me-1"></i> Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'userprofile:config' %}"
              ><i class="bx bx-bell me-1"></i> Configuration</a
            >
          </li>
        </ul>
        <div class="card mb-4">
          <h5 class="card-header">Profile Details</h5>
          <!-- Account -->
          <div class="card-body">
            <form id="formAccountSettings" method="POST" action="{% url 'userprofile:account' %}" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="d-flex align-items-start align-items-sm-center gap-4">
              <img
                src="{{ user.userprofile.avatar.url }}"
                alt="user-avatar"
                class="d-block rounded"
                height="100"
                width="100"
                id="uploadedAvatar"
              />
              <div class="button-wrapper">
                <label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
                  <span class="d-none d-sm-block">Upload new photo</span>
                  <i class="bx bx-upload d-block d-sm-none"></i>
                  <input
                    type="file"
                    id="upload"
                    name="upload"
                    class="account-file-input"
                    hidden
                    accept="image/png, image/jpeg"
                  />
                </label>
                <button type="button" class="btn btn-outline-secondary account-image-reset mb-4">
                  <i class="bx bx-reset d-block d-sm-none"></i>
                  <span class="d-none d-sm-block">Reset</span>
                </button>

                <p class="text-muted mb-0">Allowed JPG, GIF or PNG. Max size of 800K</p>
              </div>
            </div>
          </div>
          <hr class="my-0" />
          <div class="card-body">
              <div class="row">
                <div class="mb-3 col-md-6">
                  <label for="firstName" class="form-label">First Name</label>
                  <input
                    class="form-control"
                    type="text"
                    id="firstName"
                    name="firstName"
                    value="{{ user.userprofile.first_name }}"
                    autofocus
                  />
                </div>
                <div class="mb-3 col-md-6">
                  <label for="lastName" class="form-label">Last Name</label>
                  <input class="form-control" type="text" name="lastName" id="lastName" value="{{ request.user.userprofile.last_name }}" />
                </div>
                <div class="mb-3 col-md-6">
                  <label for="email" class="form-label">E-mail</label>
                  <input
                    class="form-control"
                    type="text"
                    id="email"
                    name="email"
                    value="{{ request.user.email }}"
                    placeholder="john.doe@example.com"
                  />
                </div>
                <div class="mb-3 col-md-6">
                  <label class="form-label" for="phoneNumber">Phone Number</label>
                  <div class="input-group input-group-merge">
                    <span class="input-group-text">PH (+63)</span>
                    <input
                      type="text"
                      id="phoneNumber"
                      name="phoneNumber"
                      class="form-control"
                      placeholder="202 555 0111"
                      value="{{ user.userprofile.phone_number }}"
                    />
                  </div>
                </div>
                <div class="mb-3 col-md-6">
                  <label for="html5-date-input" class="form-label">Birth Date</label>
                  <div class="col-md-12">
                    <input class="form-control" type="date" name='birthdate' value="{{ user.userprofile.birthdate|date:'Y-m-d' }}" id="html5-date-input" /></div>
                </div>
                <div class="mb-3 col-md-6">
                  <label for="address" class="form-label">Address</label>
                  <input type="text" class="form-control" id="address" value="{{ user.userprofile.address }}" name="address" placeholder="Address" />
                </div> 
                <div class="mb-3 col-md-6">
                  <label for="tin" class="form-label">TIN Number</label>
                  <input type="text" class="form-control" id="tin" value="{{user.userprofile.tin}}" name="tin" placeholder="TIN number" />
                </div>
                <div class="mb-3 col-md-6">
                  <label for="sss" class="form-label">SSS Number</label>
                  <input type="text" class="form-control" id="sss" value="{{user.userprofile.sss}}" name="sss" placeholder="SSS number" />
                </div>
                <div class="mb-3 col-md-6">
                  <label for="pagibig" class="form-label">PAGIBIG Number</label>
                  <input type="text" class="form-control" id="pagibig" value="{{user.userprofile.pagibig}}" name="pagibig" placeholder="PAGIBIG number" />
                </div>
                <div class="mb-3 col-md-6">
                  <label for="philhealth" class="form-label">PHILHEALTH Number</label>
                  <input type="text" class="form-control" id="philhealth" value="{{user.userprofile.philhealth}}" name="philhealth" placeholder="PHILHEALTH number" />
                </div>
                <div class="divider">
                  <div class="divider-text">Emergency</div>
                </div>
                <div class="mb-3 col-md-6">
                  <label for="emergencyContact" class="form-label">Emergency Contact Person</label>
                  <input type="text" class="form-control" id="emergencyContact" value="{{user.userprofile.emergency_contact}}" name="emergencyContact" placeholder="Emergency Contact Person" />
                </div>
                <div class="mb-3 col-md-6">
                  <label for="emergencyContactNumber" class="form-label">Emergency Contact Number</label>
                  <input type="text" class="form-control" id="emergencyContactNumber" value="{{user.userprofile.emergency_contact_number}}" name="emergencyContactNumber" placeholder="Emergency Contact Person" />
                </div>
                                       
              <div class="mt-2">
                <button type="submit" name='buttonUpdateAccount' class="btn btn-primary me-2">Save changes</button>
                <button type="reset" class="btn btn-outline-secondary">Cancel</button>
              </div>
          </div>
        </form>
          <!-- /Account -->
        </div>
        <div class="card">
          <h5 class="card-header">Delete Account</h5>
          <div class="card-body">
            <div class="mb-3 col-12 mb-0">
              <div class="alert alert-warning">
                <h6 class="alert-heading fw-bold mb-1">Are you sure you want to delete your account?</h6>
                <p class="mb-0">Once you delete your account, there is no going back. Please be certain.</p>
              </div>
            </div>
            <form id="formAccountDeactivation" action="{% url 'userprofile:deactivate' %}" method="POST">
              {% csrf_token %}
              <div class="form-check mb-3">
                <input
                  class="form-check-input"
                  type="checkbox"
                  name="accountActivation"
                  id="accountActivation"
                />
                <label class="form-check-label" for="accountActivation"
                  >I confirm my account deactivation</label
                >
              </div>
              <button type="submit" id="buttonDeactivate" name='buttonDeactivate' disabled class="btn btn-danger deactivate-account">Deactivate Account</button>
            </form>
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

{% block javascript %}
<script src="{% static 'assets/js/pages-account-settings-account.js' %}"></script>

<script>
$('#accountActivation').change(function () {
  $('#buttonDeactivate').prop("disabled", !this.checked);
}).change()
</script>
{% endblock javascript %}